# Generated by Django 4.2.6 on 2023-11-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('DONE', 'Done')], default='TODO', max_length=10)),
            ],
        ),
    ]
